
- name: dataset
  key: [dataset_filename]
  values: [trec2007-1607201347, trec2007-1607252257, trec2007-1607252259]

- name: classifier
  key: [classifier, type]
  values:
    - adaline
    - logistic regression
    - naive bayes

- name: attack
  key: [attack, type]
  values:
    - dictionary
    - empty
    - ham
#   - focussed

- name: '% poisoned'
  key: [attack, parameters, percentage_samples_poisoned]
  values:
    - .0
    - .5

  #- name: learning rate
  #  key: [classifier, training_parameters, learning_rate]
  #  values:
  #    - .5
  #    - .2
  #    - .1
  #    - .05
  #
  #- name: GD method
  #  key: [classifier, training_parameters, gradient_descent_method]
  #  values:
  #    - stochastic
  #    - mini-batch
  #    - batch
  #
  #- name: GD batch size
  #  key: [classifier, training_parameters, batch_size]
  #  values:
  #    - 10
  #    - 50
  #    - 100
  #    - 500

