
version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s.%(msecs)03d __%(name)s__ %(levelname)s: %(message)s'
    datefmt: '%b %d %H:%M:%S'
  concise:
    format: '%(asctime)s.%(msecs)03d %(name)s: %(message)s'
    datefmt: '%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: concise
    stream: ext://sys.stdout
  batch:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: null
    encoding: utf8
    mode: w

root:
  level: NOTSET
  propagate: false
  handlers: [console, batch]

